export const START_LEAD_EDIT = 'START_LEAD_EDIT';
export const CHANGE_LEAD_NOTE = 'CHANGE_LEAD_NOTE';
export const SHOW_NOTES_INPUT = 'SHOW_NOTES_INPUT';

export const CLEAR_CONTROLS = 'CLEAR_CONTROLS';
export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_VISIBLE = 'SET_VISIBLE';

export const SET_MODAL = 'SET_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLEAR_MODAL = 'CLEAR_MODAL';

export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_PASSWORD_PENDING = 'UPDATE_PASSWORD_PENDING';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_INCREMENT_STEP = 'SIGNUP_INCREMENT_STEP';
export const SIGNUP_DECREMENT_STEP = 'SIGNUP_DECREMENT_STEP';
export const SIGNUP_ADD_INFO = 'SIGNUP_ADD_INFO';
export const SIGNUP_ADD_BILLING = 'SIGNUP_ADD_BILLING';
export const SIGNUP_ADD_COUPON = 'SIGNUP_ADD_COUPON';
export const SIGNUP_CANCEL = 'SIGNUP_CANCEL';

export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const GET_CHANNELS_PENDING = 'GET_CHANNELS_PENDING';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAILURE = 'GET_CHANNELS_FAILURE';

export const ADD_CHANNEL_PENDING = 'ADD_CHANNEL_PENDING';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_FAILURE = 'ADD_CHANNEL_FAILURE';

export const DELETE_CHANNEL_PENDING = 'DELETE_CHANNEL_PENDING';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_FAILURE = 'DELETE_CHANNEL_FAILURE';

export const GET_NOTIF_PREFS_PENDING = 'GET_NOTIF_PREFS_PENDING';
export const GET_NOTIF_PREFS_SUCCESS = 'GET_NOTIF_PREFS_SUCCESS';
export const GET_NOTIF_PREFS_FAILURE = 'GET_NOTIF_PREFS_FAILURE';

export const NOTIF_SUBSCRIBE_PENDING = 'NOTIF_SUBSCRIBE_PENDING';
export const NOTIF_SUBSCRIBE_SUCCESS = 'NOTIF_SUBSCRIBE_SUCCESS';
export const NOTIF_SUBSCRIBE_FAILURE = 'NOTIF_SUBSCRIBE_FAILURE';

export const NOTIF_UNSUBSCRIBE_PENDING = 'NOTIF_UNSUBSCRIBE_PENDING';
export const NOTIF_UNSUBSCRIBE_SUCCESS = 'NOTIF_UNSUBSCRIBE_SUCCESS';
export const NOTIF_UNSUBSCRIBE_FAILURE = 'NOTIF_UNSUBSCRIBE_FAILURE';
