export const GET_LEADS_PENDING = 'GET_LEADS_PENDING';
export const GET_LEADS_FAILURE = 'GET_LEADS_FAILURE';
export const GET_LEADS_SUCCESS = 'GET_LEADS_SUCCESS';

export const GET_LISTINGS_PENDING = 'GET_LISTINGS_PENDING';
export const GET_LISTINGS_FAILURE = 'GET_LISTINGS_FAILURE';
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';

export const MARK_VIEWED_PENDING = 'MARK_VIEWED_PENDING';
export const MARK_VIEWED_FAILURE = 'MARK_VIEWED_FAILURE';
export const MARK_VIEWED_SUCCESS = 'MARK_VIEWED_SUCCESS';

export const MARK_UNREAD_PENDING = 'MARK_UNREAD_PENDING';
export const MARK_UNREAD_FAILURE = 'MARK_UNREAD_FAILURE';
export const MARK_UNREAD_SUCCESS = 'MARK_UNREAD_SUCCESS';

export const MARK_MULTI_READ_PENDING = 'MARK_MULTI_READ_PENDING';
export const MARK_MULTI_READ_SUCCESS = 'MARK_MULTI_READ_SUCCESS';
export const MARK_MULTI_READ_FAILURE = 'MARK_MULTI_READ_FAILURE';

export const DELETE_LEAD_PENDING = 'DELETE_LEAD_PENDING';
export const DELETE_LEAD_FAILURE = 'DELETE_LEAD_FAILURE';
export const DELETE_LEAD_SUCCESS = 'DELETE_LEAD_SUCCESS';

export const DELETE_LISTING_PENDING = 'DELETE_LISTING_PENDING';
export const DELETE_LISTING_FAILURE = 'DELETE_LISTING_FAILURE';
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';

export const DELETE_LEADS_PENDING = 'DELETE_LEADS_PENDING';
export const DELETE_LEADS_FAILURE = 'DELETE_LEADS_FAILURE';
export const DELETE_LEADS_SUCCESS = 'DELETE_LEADS_SUCCESS';

export const MARK_STARRED_PENDING = 'MARK_STARRED_PENDING';
export const MARK_STARRED_SUCCESS = 'MARK_STARRED_SUCCESS';
export const MARK_STARRED_FAILURE = 'MARK_STARRED_FAILURE';
export const REMOVE_STAR_PENDING = 'REMOVE_STAR_PENDING';
export const REMOVE_STAR_SUCCESS = 'REMOVE_STAR_SUCCESS';
export const REMOVE_STAR_FAILURE = 'REMOVE_STAR_FAILURE';

export const CHECK_LEAD = 'CHECK_LEAD';
export const CHECK_LEADS = 'CHECK_LEADS';
export const UNCHECK_LEAD = 'UNCHECK_LEAD';
export const CLEAR_CHECKED_LEADS = 'CLEAR_CHECKED_LEADS';

export const START_LEAD_EDIT = 'START_LEAD_EDIT';
export const CHANGE_LEAD_NOTE = 'CHANGE_LEAD_NOTE';
export const SHOW_NOTES_INPUT = 'SHOW_NOTES_INPUT';

export const UPDATE_LEAD_PENDING = 'UPDATE_LEAD_PENDING';
export const UPDATE_LEAD_SUCCESS = 'UPDATE_LEAD_SUCCESS';
export const UPDATE_LEAD_FAILURE = 'UPDATE_LEAD_FAILURE';
export const UPDATE_LEAD_CANCEL = 'UPDATE_LEAD_CANCEL';

export const LOAD_LEAD_CONTROLS = 'LOAD_LEAD_CONTROLS';
export const LOAD_LISTING_CONTROLS = 'LOAD_LISTING_CONTROLS';
export const CLEAR_CONTROLS = 'CLEAR_CONTROLS';

export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_VISIBLE = 'SET_VISIBLE';

export const SET_MODAL = 'SET_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLEAR_MODAL = 'CLEAR_MODAL';

export const START_LISTING_EDIT = 'START_LISTING_EDIT';
export const UPDATE_LISTING_PENDING = 'UPDATE_LISTING_PENDING';
export const UPDATE_LISTING_SUCCESS = 'UPDATE_LISTING_SUCCESS';
export const UPDATE_LISTING_FAILURE = 'UPDATE_LISTING_FAILURE';
export const UPDATE_LISTING_CANCEL = 'UPDATE_LISTING_CANCEL';

export const CREATE_LISTING_PENDING = 'CREATE_LISTING_PENDING';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_FAILURE = 'CREATE_LISTING_FAILURE';

export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const REMOVE_AVATAR_PENDING = 'REMOVE_AVATAR_PENDING';
export const REMOVE_AVATAR_SUCCESS = 'REMOVE_AVATAR_SUCCESS';
export const REMOVE_AVATAR_FAILURE = 'REMOVE_AVATAR_FAILURE';

export const ADD_AVATAR_PENDING = 'ADD_AVATAR_PENDING';
export const ADD_AVATAR_SUCCESS = 'ADD_AVATAR_SUCCESS';
export const ADD_AVATAR_FAILURE = 'ADD_AVATAR_FAILURE';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_PASSWORD_PENDING = 'UPDATE_PASSWORD_PENDING';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REFRESH_TOKEN_PENDING = 'REFRESH_TOKEN_PENDING';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const UPDATE_KEYWORD_PENDING = 'UPDATE_KEYWORD_PENDING';
export const UPDATE_KEYWORD_SUCCESS = 'UPDATE_KEYWORD_SUCCESS';
export const UPDATE_KEYWORD_FAILURE = 'UPDATE_KEYWORD_FAILURE';

export const GET_KEYWORD_PENDING = 'GET_KEYWORD_PENDING';
export const GET_KEYWORD_SUCCESS = 'GET_KEYWORD_SUCCESS';
export const GET_KEYWORD_FAILURE = 'GET_KEYWORD_FAILURE';

export const SIGNUP_INCREMENT_STEP = 'SIGNUP_INCREMENT_STEP';
export const SIGNUP_DECREMENT_STEP = 'SIGNUP_DECREMENT_STEP';
export const SIGNUP_ADD_INFO = 'SIGNUP_ADD_INFO';
export const SIGNUP_ADD_BILLING = 'SIGNUP_ADD_BILLING';
export const SIGNUP_ADD_COUPON = 'SIGNUP_ADD_COUPON';
export const SIGNUP_CANCEL = 'SIGNUP_CANCEL';

export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const GET_INVOICES_PENDING = 'GET_INVOICES_PENDING';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAILURE = 'GET_INVOICES_FAILURE';

export const UPDATE_CARD_PENDING = 'UPDATE_CARD_PENDING';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILURE = 'UPDATE_CARD_FAILURE';

export const GET_CHANNELS_PENDING = 'GET_CHANNELS_PENDING';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAILURE = 'GET_CHANNELS_FAILURE';

export const ADD_CHANNEL_PENDING = 'ADD_CHANNEL_PENDING';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_FAILURE = 'ADD_CHANNEL_FAILURE';

export const DELETE_CHANNEL_PENDING = 'DELETE_CHANNEL_PENDING';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_FAILURE = 'DELETE_CHANNEL_FAILURE';

export const GET_NOTIF_PREFS_PENDING = 'GET_NOTIF_PREFS_PENDING';
export const GET_NOTIF_PREFS_SUCCESS = 'GET_NOTIF_PREFS_SUCCESS';
export const GET_NOTIF_PREFS_FAILURE = 'GET_NOTIF_PREFS_FAILURE';

export const NOTIF_SUBSCRIBE_PENDING = 'NOTIF_SUBSCRIBE_PENDING';
export const NOTIF_SUBSCRIBE_SUCCESS = 'NOTIF_SUBSCRIBE_SUCCESS';
export const NOTIF_SUBSCRIBE_FAILURE = 'NOTIF_SUBSCRIBE_FAILURE';

export const NOTIF_UNSUBSCRIBE_PENDING = 'NOTIF_UNSUBSCRIBE_PENDING';
export const NOTIF_UNSUBSCRIBE_SUCCESS = 'NOTIF_UNSUBSCRIBE_SUCCESS';
export const NOTIF_UNSUBSCRIBE_FAILURE = 'NOTIF_UNSUBSCRIBE_FAILURE';
